OpenZeppelin/openzeppelin-relayer

- .github/RELEASE.md
- Rename .github/README.md to .github/RELEASE.md
> chore: Change release readme to release readme

- docker-compose.yaml
> fix: Docker Compose

- .github/workflows/release-please.yml
- Dockerfile.production
- docker-compose.yaml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/index.adoc
- Fix workflow and missing libs in dockerfile
> chore: Fix workflow and missing libs in docker file

- .github/release-please/.config.json
- .github/workflows/release-please.yml
- Fix skip releases, currently if there are no user related changes detected by config file...release please skips creating the PR
Fixes https://github.com/OpenZeppelin/openzeppelin-relayer/actions/runs/14321650196/job/40139581257#step:7:52
> fix: Skip releases with release please

- .github/workflows/release-please.yml
> fix: Release merge conflicts

- .github/workflows/cla.yml
> fix: CLA labels

- .github/workflows/release-docs.yml
- .yamlfix.toml
- docs/antora.yml
> chore: update the docs branch

- README.md
Update typo in main README file
> chore: plat-0000 update readme, fix typo

- Cargo.toml
- src/domain/relayer/mod.rs
- src/domain/relayer/stellar/stellar_relayer.rs
- src/domain/transaction/mod.rs
- src/domain/transaction/stellar/stellar_transaction.rs
- src/services/provider/mod.rs
- src/services/provider/stellar/mod.rs
This PR adds an RPC provider service for stellar network
> feat: Stellar RPC service

- src/domain/relayer/mod.rs
- src/domain/relayer/stellar/stellar_relayer.rs
- src/domain/transaction/mod.rs
- src/domain/transaction/stellar/mod.rs
- src/domain/transaction/stellar/stellar_transaction.rs
- src/domain/transaction/stellar/utils.rs
- src/jobs/job_producer.rs
- src/models/error/mod.rs
- src/models/error/provider.rs
- src/models/error/transaction.rs
- src/models/network/stellar/named_network.rs
- src/models/transaction/repository.rs
- src/models/transaction/response.rs
- src/models/transaction/stellar_types.rs
- src/services/provider/stellar/mod.rs
- src/services/signer/stellar/local_signer.rs
This update introduces the core logic for submitting Stellar transactions through the relayer. Key highlights:
- Stellar Transaction Submission: Implements the full process for preparing, signing, simulating (when required), and submitting Stellar transactions. Handles transaction status updates and notification dispatch.
- Sequence Management: Adds logic to manage and synchronize sequence numbers using a transaction counter service, ensuring correct transaction ordering.
- Error Handling: Improves error propagation and handling for provider errors, sequence synchronization, and transaction failures.
> feat: Stellar transaction submission

- .github/workflows/release-please.yml
- .github/workflows/rust-docs-url.yml
> chore: Minor fixes to ci releases

- src/domain/relayer/mod.rs
- src/domain/transaction/mod.rs
- src/services/provider/mod.rs
- src/services/provider/stellar/mod.rs
Adds suppor to for the new PRC config to stellar
> feat: Stellar RPC config

- .github/workflows/scorecard.yml
> chore: add Scorecard workflow

- .github/workflows/ci.yaml
- README.md
> chore: add the scorecard badge

- docs/modules/ROOT/pages/solana.adoc
This PR improved newly introduced solana docs page to list all relevant info about solana integration at one place.
> docs: plat-xxxx improve solana page, add all relevant info

- src/domain/relayer/stellar/stellar_relayer.rs
- Added the `get_balance` method to the `StellarRelayer`
> feat: Implement get_balance method for StellarRelayer

- README.md
- docs/modules/ROOT/pages/api_reference.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/roadmap.adoc
- Added Stellar to the list of supported networks in README and API reference.
- Enhanced documentation for Stellar API interactions, including transaction submission, retrieval, and listing.
- Updated roadmap to reflect the current status and upcoming features for Stellar support.
> docs: Update README and API reference for Stellar support

- .github/workflows/release-docker.yml
- DOCKER_README.md
- README.md
- Add overview to dockerhub for users to run docker images.
> docs: Add overview to dockerhub

- .github/workflows/ci.yaml
- Dockerfile.development
- Dockerfile.production
> fix: docker-scan - chainguard issue

- src/api/controllers/mod.rs
- src/api/controllers/plugin.rs
- src/api/routes/mod.rs
- src/api/routes/plugin.rs
- src/domain/transaction/evm/price_calculator.rs
- src/jobs/retry_backoff.rs
- src/models/plugin.rs
- src/models/relayer/rpc_config.rs
- src/repositories/plugin.rs
- src/repositories/relayer.rs
- src/services/mod.rs
- src/services/plugins/mod.rs
- Adds support to plugin call endpoint
- Adds plugins controller
- Adds plugins service
> feat: Add plugins call endpoint

- src/models/transaction/repository.rs
- Added validation to ensure that the memo is None when using InvokeHostFunction operations.
> fix: Add memo validation for InvokeHostFunction

- docs/modules/ROOT/pages/api_reference.adoc
- src/domain/transaction/stellar/utils.rs
- src/models/transaction/mod.rs
- src/models/transaction/repository.rs
- src/models/transaction/stellar/asset.rs
- src/models/transaction/stellar/host_function.rs
- src/models/transaction/stellar/memo.rs
- src/models/transaction/stellar/mod.rs
- src/models/transaction/stellar/operation.rs
- Flattened InvokeHostFunction operations - Split into three distinct operations:
- InvokeContract - Contract invocations
- CreateContract - Contract creation
- UploadWasm - WASM code uploads
- Added temporary fix for stellar-xdr deserialization issue with u64/i64 values provided as strings
- Updated docs with new schema examples
> refactor: Update Stellar operations and API docs

- docs/modules/ROOT/pages/roadmap.adoc
- plugins/lib/plugin.ts
- src/api/routes/docs/mod.rs
- src/api/routes/docs/plugin_docs.rs
- src/models/plugin.rs
- src/openapi.rs
- src/services/plugins/mod.rs
- src/services/plugins/relayer_api.rs
- src/services/plugins/runner.rs
- src/services/plugins/script_executor.rs
- src/services/plugins/socket.rs
Just adds doc comments to scripts + some openapi docs
> docs: Add comment docs for scripts in plugins

- plugins/lib/plugin.ts
- src/services/plugins/mod.rs
- src/services/plugins/runner.rs
- src/services/plugins/script_executor.rs
- src/services/plugins/socket.rs
Fixes merge conflicts of https://github.com/OpenZeppelin/openzeppelin-relayer/pull/303
> feat: Pass arbitrary payloads to script exectution

- plugins/examples/example.ts
- plugins/jest.config.js
- plugins/lib/logger.ts
- plugins/package.json
- plugins/pnpm-lock.yaml
- plugins/tests/lib/logger.test.ts
- plugins/tests/lib/plugin.test.ts
- plugins/tests/setup.ts
- plugins/tsconfig.test.json
- Fixes the plugin resturn value parsing.
- Adds tests for the plugins internal typescript lib
> fix: Plugin result + adds tests for plugin ts lib

- .github/workflows/release-sbom.yml
> fix: SBOM upload error

- .github/workflows/release-docker.yml
> fix: Docker readme file

- src/constants/evm_transaction.rs
- src/models/transaction/request/evm.rs
- src/utils/transaction.rs
This PR will add intrinsic gas validation when gas_limit is defined in request.
> feat: add evm intrinsic gas_limit validation

- .github/workflows/semgrep.yml
[PS-13](https://linear.app/openzeppelin-development/issue/PS-13/semgrep-cicd-integration)
Fix env var error value in `semgrep.yml`
> fix: Correct env var value in semgrep.yml

- src/domain/transaction/stellar/prepare/fee_bump.rs
- src/domain/transaction/stellar/prepare/mod.rs
- src/domain/transaction/stellar/prepare/operations.rs
- src/domain/transaction/stellar/prepare/unsigned_xdr.rs
- src/domain/transaction/stellar/status.rs
- src/domain/transaction/stellar/stellar_transaction.rs
- src/domain/transaction/stellar/submit.rs
- src/models/transaction/repository.rs
- Added functionality to update Stellar transaction data with the actual fee charged by the network.
- Refactored `finalize_transaction_state` to accept a `TransactionUpdateRequest` for better clarity and flexibility.
- Updated transaction handling methods to utilize the new fee update logic, ensuring accurate transaction status updates.
> feat: Enhance Stellar tx handling with fee updates

- config/networks/stellar.json
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/network_configuration.adoc
- docs/modules/ROOT/pages/stellar.adoc
- Changed RPC URL for Stellar mainnet from "https://horizon.stellar.org" to "https://mainnet.sorobanrpc.com" in configuration files.
- Added a new documentation page for Stellar integration, detailing features, supported networks, and API usage.
- Updated navigation to include the new Stellar documentation page.
> feat: Update Stellar network config and docs

- config/networks/abstract.json
- config/networks/other-l1s.json
- config/networks/sophon.json
- Add network config files for Fuse and Abstract chains.
- Fixing flaky RPC for gnosis and adding gnosis chiado testnet
-  Add network config file for Sophon
> chore: Adding support for Fuse, Abstract and Sophon

- src/api/controllers/relayer.rs
- src/domain/relayer/solana/dex/mod.rs
- src/domain/relayer/solana/rpc/methods/fee_estimate.rs
- src/domain/relayer/solana/rpc/methods/get_supported_tokens.rs
- src/domain/relayer/solana/rpc/methods/prepare_transaction.rs
- src/domain/relayer/solana/rpc/methods/test_setup.rs
- src/domain/relayer/solana/rpc/methods/transfer_transaction.rs
- src/domain/relayer/solana/rpc/methods/utils.rs
- src/domain/relayer/solana/rpc/methods/validations.rs
- src/domain/relayer/solana/solana_relayer.rs
- src/models/mod.rs
- src/models/notification/request.rs
- src/models/relayer/config.rs
- src/models/relayer/mod.rs
- src/models/relayer/repository.rs
- src/models/relayer/request.rs
- src/models/relayer/response.rs
- src/models/signer/request.rs
Revert model name changes to prevent sdk breaking changes.
Decorate response fields with missing schema macros.
https://github.com/OpenZeppelin/openzeppelin-relayer-sdk/pull/134/
> feat: Plat-6864 add sdk examples for newly exposed api
